#!/usr/bin/env bash

set -e
cd "$(dirname "$0")/.."

if [ -z "$1" -o "$1" = "elisp" ]
then
    cask exec ert-runner --quiet
fi

if [ -z "$1" -o "$1" = "python" ]
then
    flake8 elpy
    mypy
    black elpy --check
    isort elpy --check
    coverage run -m unittest discover elpy
    coverage html -d ~/Public/elpy-coverage.html
fi
