name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - "26.1"
          - "26.2"
          - "26.3"
          - "27.1"
        python_version:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Emacs ${{ matrix.emacs_version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Set up Cask
      uses: conao3/setup-cask@master
      with:
          version: 'snapshot'
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version : ${{ matrix.python_version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --upgrade
        pip install -r requirements-rpc.txt --upgrade
        pip install -r requirements-dev.txt --upgrade
        if [[ ${{ matrix.python_version }} > 3.5 ]] ; then
          pip install -r requirements-rpc3.6.txt --upgrade ;
        fi
        if [[ ${{ matrix.python_version }} < 3 ]] ; then
          pip install -r requirements-dev2.txt --upgrade ;
        fi
        pip install coveralls
        python -m virtualenv $HOME/.virtualenvs/elpy-test-venv
    # Run tests
    - name: Run Emacs tests
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        command: cask install ; PYTHONPATH="`pwd`" cask exec ert-runner --reporter ert+duration
    - name: Run Python tests
      run: nosetests
